name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Build exporter and load locally
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/ebpf-userspace-exporter
          tag_with_sha: true
          tag_with_ref: true
